version: "3.7"
services:
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: "gin-admin"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - rddata:/data
volumes:
  pgdata:
  rddata:
