version: "3.7"
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/dll/mosquitto_payload_modification.so:/mosquitto/dll/mosquitto_payload_modification.so
      - ./mosquitto/dll/grpc_auth.so:/mosquitto/dll/grpc_auth.so
      - ./mosquitto:/mosquitto
