version: "3.7"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "5010:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
