version: '3.7'
services:
  minio:
    image: bitnami/minio:latest
    hostname: minio
    ports:
      - "9000:9000"
      - "9010:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SERVER_ACCESS_KEY: "toQVQar56ALcXP4k0oNv"
      MINIO_SERVER_SECRET_KEY: "7styo8rKK73AqZZlJ9qC4rtIJH74NOtnmG9YD9oN"
    volumes:
      - data:/data
volumes:
  data: