name: influxdb3-stack

services:
  influxdb3-core:
    container_name: influxdb3-core
    image: crpi-14aq4ypr9y9smv5q.cn-hangzhou.personal.cr.aliyuncs.com/fssq/influxdb:3-core
    user: "root"
    ports:
      - "8181:8181"
    environment:
      - TZ=Asia/Shanghai # 同步时区，确保数据时间戳准确
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      # 修复点：改用 Docker 命名的 Volume，彻底解决 13 Permission Denied 报错
      - influxdb3-data:/var/lib/influxdb3/data
      - influxdb3-plugins:/var/lib/influxdb3/plugins
    logging:
      driver: "json-file"
      options:
        max-size: "50m" # 限制日志大小，防止撑爆磁盘
        max-file: "3"
    restart: unless-stopped

  influxdb3-ui:
    image: crpi-14aq4ypr9y9smv5q.cn-hangzhou.personal.cr.aliyuncs.com/fssq/influxdb3-ui:latest # UI 镜像
    container_name: influxdb3-ui
    ports:
      - "8888:80" # UI Web 访问端口
      - "8889:8888" # Admin API 通信端口
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - influxdbUI_data:/db:rw # UI 数据存放，使用 Volume 确保重启不丢失
    command:
      - --mode=admin # 开启 Admin 模式，支持全量管理功能
    depends_on:
      - influxdb3-core # 确保数据库先启动
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped

volumes:
  # 修复点：在全局声明刚刚添加的数据卷
  influxdb3-data:
  influxdb3-plugins:
  influxdbUI_data:
