services:
  influxdb:
    image: quay.io/influxdb/influxdb3-core:latest
    container_name: influxdb3
    ports:
      - "8181:8181"      # InfluxDB 服务端口，容器内默认8181
    volumes:
      - influxdb-data:/var/lib/influxdb3
    command:
      - serve
      - --node-id=host01
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    restart: unless-stopped

  influxdb-ui:
    image: crpi-14aq4ypr9y9smv5q.cn-hangzhou.personal.cr.aliyuncs.com/fssq/influxdb3-ui
    container_name: influxdb3-ui
    ports:
      - "8888:80"        # UI 默认 http 端口80，映射到宿主机8888端口
      - "8889:8888"      # Admin API 端口
    command:
      - --mode=admin
    restart: unless-stopped

volumes:
  influxdb-data:
